# @package _global_

algo:
  name: td3
  backbone_cls: mlp
  actor_update_freq: 1
  target_update_freq: 1
  discount: 0.99
  ema: 0.005
  actor_hidden_dims: [512, 512, 512]
  actor_activation: relu
  critic_hidden_dims: [512, 512, 512]
  critic_activation: relu
  critic_ensemble_size: 2
  actor_lr: 0.0003
  critic_lr: 0.0003
  clip_grad_norm: null
  target_policy_noise: 0.2
  noise_clip: 0.3
  exploration_noise: 0.2
