defaults:
  - /mujoco_config_cfg_def@_here_
  - _self_
  - algo: base # raise error if algo is not specified
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

seed: 0
device: '0'
task: ???
frame_skip: 1
num_train_envs: 1
utd: 1
batch_size: 256
buffer_size: 1_000_000
lap_alpha: 0.0
norm_obs: false
train_frames: 1_000_000
warmup_frames: 5_000
random_frames: 5_000
eval_frames: 10_000
log_frames: 1_000
lap_reset_frames: 250
log:
  dir: logs
  tag: debug
  save_ckpt: false
  save_video: false
  project: ???
  entity: ???
eval:
  num_episodes: 10
  num_samples: 1
