defaults:
  - /config_cfg_def@_here_
  - _self_
  - algo: base # raise error if algo is not specified
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

seed: 0
device: '0'
task: ???
pretrain_only: false
pretrain_steps: 0
train_steps: 100_000
load: null
log:
  dir: logs
  tag: debug
  interval: 500
  save_interval: 10000
  stats_interval: 2000
  save_ckpt: true
  save_video: false
  project: ???
  entity: ???
data:
  batch_size: 512
  scan: true
eval:
  interval: 10000


