# @package _global_

algo:
  name: dacer
  critic_hidden_dims: [256, 256]
  critic_activation: relu
  critic_ensemble_size: 2
  critic_lr: 0.0001
  alpha_lr: 0.03
  discount: 0.99
  ema: 0.005
  entropy_num_samples: 200
  update_actor_every: 2
  update_alpha_every: 10000
  reward_scale: 0.2
  noise_scaler: ${oc.select:algo.noise_scaler_dict.${task},0.1}
  noise_scaler_dict:
    HalfCheetah-v5: 0.15
    Humanoid-v5: 0.15
  diffusion:
    time_dim: 64
    mlp_hidden_dims: [256, 256, 256]
    lr: 0.0001
    end_lr: null
    lr_decay_steps: null
    lr_decay_begin: null
    steps: 20
    clip_sampler: true
    x_min: -1.0
    x_max: 1.0
