# @package _global_

algo:
  name: dpmd
  critic_hidden_dims: [256, 256]
  critic_activation: relu
  critic_lr: 0.0003
  temp_lr: 0.0003
  discount: 0.99
  num_samples: 10
  num_particles: 32
  target_kl: 1.5
  reweight: exp
  ema: 0.005
  old_policy_update_interval: 1000
  diffusion:
    time_dim: 64
    mlp_hidden_dims: [256, 256]
    lr: 0.0003
    end_lr: null
    lr_decay_steps: null
    lr_decay_begin: null
    steps: 20
    clip_sampler: true
    x_min: -1.0
    x_max: 1.0
    solver: ddpm
