# @package _global_

algo:
  name: qsm
  backbone_cls: mlp
  critic_hidden_dims: [256, 256]
  critic_activation: relu
  critic_lr: 0.0003
  discount: 0.99
  num_samples: 10
  ema: 0.005
  temp: 0.1
  diffusion:
    backbone_cls: ${algo.backbone_cls}
    activation: mish
    time_dim: 64
    hidden_dims: [256, 256, 256]
    lr: 0.0003
    end_lr: null
    lr_decay_steps: null
    lr_decay_begin: null
    steps: 20
    clip_sampler: true
    x_min: -1.0
    x_max: 1.0
    solver: ddpm
