# @package _global_

algo:
  name: td3
  backbone_cls: mlp
  discount: 0.99
  ema: 0.005
  actor_hidden_dims: [256, 256]
  critic_hidden_dims: [256, 256]
  activation: relu
  critic_ensemble_size: 2
  actor_lr: 0.0003
  critic_lr: 0.0003
  clip_grad_norm: null
  actor_update_freq: 2
  target_update_freq: 2
  target_policy_noise: 0.2
  noise_clip: 0.5
  exploration_noise: 0.1
