# @package _global_
algo:
  name: genpo
  num_envs: 1024
  rollout_length: 24
  backbone_cls: mlp
  critic_hidden_dims: [256, 256, 256]
  critic_activation: elu
  critic_lr: 0.001
  gamma: 0.99
  gae_lambda: 0.95
  clip_epsilon: 0.2
  reward_scaling: 1.0
  normalize_advantage: true
  num_minibatches: 4
  num_epochs: 4
  batch_size: 6144
  clip_grad_norm: 1.0
  entropy_coeff: 0.01
  compress_coef: 0.01
  flow:
    activation: elu
    hidden_dims: [256, 256, 256]
    time_dim: 32
    steps: 5
    mix_para: 0.9
    lr: 0.0001

train_frames: 100_000_000
