# @package _global_

algo:
  name: ppo
  num_envs: 4096
  rollout_length: 24
  backbone_cls: mlp
  actor_hidden_dims: [256, 256, 256]
  critic_hidden_dims: [256, 256, 256]
  activation: elu
  actor_lr: 0.0001
  critic_lr: 0.001
  gamma: 0.99
  gae_lambda: 0.95
  clip_epsilon: 0.2
  entropy_coeff: 0.0001
  reward_scaling: 1.0
  normalize_advantage: true
  num_minibatches: 4
  num_epochs: 4
  batch_size: 24576
  clip_grad_norm: 1.0
